### PR TITLE
Fix imx6 build

### PR DESCRIPTION
**Pull request by Kivutar**
Maybe we should also add "rpi" and "armv" to this test.

### CODE REVIEW

**Comment by Alcaro** [comment]
>+ifeq (,$(findstring android,$(platform)) imx6)

As far as I understand Makefiles, that will compare the empty string to "android imx6" or "imx6" depending on what that findstring test returns. While it may fix some platforms, it will break others.

**Comment by sergiobenrocha2** [comment]
I think this will work better:

```
ifeq (,$(filter $(platform), armv imx6 android))
```

**Comment by Kivutar** [comment]
I agree, can you update your PR with this please?

**Comment by sergiobenrocha2** [comment]
Yup

**Pull request closed without merging**
