### PR TITLE
Merge https://github.com/hrydgard/ppsspp (DO NOT MERGE)

### PR DESCRIPTION
**Pull request by orbea**
This is just an attempt and incomplete, I'm making this PR now in hopes someone more experienced with programming can try their hand at the final bit where libretro.cpp won't compile. Here are the errors.

```
../libretro/libretro.cpp:51:8: error: ‘FBO’ does not name a type
 static FBO *libretro_framebuffer;
        ^
../libretro/libretro.cpp:61:32: error: ‘SystemProperty’ was not declared in this scope
 std::string System_GetProperty(SystemProperty prop) { return ""; }
                                ^
../libretro/libretro.cpp:61:53: error: expected ‘,’ or ‘;’ before ‘{’ token
 std::string System_GetProperty(SystemProperty prop) { return ""; }
                                                     ^
../libretro/libretro.cpp:62:27: error: ‘SystemProperty’ was not declared in this scope
 int System_GetPropertyInt(SystemProperty prop) { return -1; }
                           ^
../libretro/libretro.cpp:62:48: error: expected ‘,’ or ‘;’ before ‘{’ token
 int System_GetPropertyInt(SystemProperty prop) { return -1; }
                                                ^
../libretro/libretro.cpp: In function ‘void NativeRender()’:
../libretro/libretro.cpp:66:28: error: ‘libretro_framebuffer’ was not declared in this scope
    fbo_override_backbuffer(libretro_framebuffer);
                            ^
../libretro/libretro.cpp:66:48: error: ‘fbo_override_backbuffer’ was not declared in this scope
    fbo_override_backbuffer(libretro_framebuffer);
                                                ^
../libretro/libretro.cpp:68:4: error: ‘glstate’ was not declared in this scope
    glstate.depthWrite.set(GL_TRUE);
    ^
../libretro/libretro.cpp:72:20: error: ‘ReapplyGfxState’ was not declared in this scope
    ReapplyGfxState();
                    ^
../libretro/libretro.cpp:89:18: error: ‘fbo_unbind’ was not declared in this scope
       fbo_unbind();
                  ^
../libretro/libretro.cpp: At global scope:
../libretro/libretro.cpp:112:7: error: ‘bool LibretroHost::InitGraphics(std::string*)’ marked ‘override’, but does not override
  bool InitGraphics(std::string *error_message) override { return true; }
       ^
../libretro/libretro.cpp: In function ‘void initialize_gl()’:
../libretro/libretro.cpp:326:4: error: ‘glstate’ was not declared in this scope
    glstate.Initialize();
    ^
../libretro/libretro.cpp:327:22: error: ‘CheckGLExtensions’ was not declared in this scope
    CheckGLExtensions();
                      ^
../libretro/libretro.cpp: In function ‘void context_reset()’:
../libretro/libretro.cpp:342:15: error: ‘gl_lost’ was not declared in this scope
       gl_lost();
               ^
../libretro/libretro.cpp:346:7: error: ‘glstate’ was not declared in this scope
       glstate.Restore();
       ^
../libretro/libretro.cpp: In function ‘void check_variables()’:
../libretro/libretro.cpp:448:19: error: ‘struct Config’ has no member named ‘bSetRoundingMode’
          g_Config.bSetRoundingMode = true;
                   ^
../libretro/libretro.cpp:450:19: error: ‘struct Config’ has no member named ‘bSetRoundingMode’
          g_Config.bSetRoundingMode = false;
                   ^
../libretro/libretro.cpp:453:19: error: ‘struct Config’ has no member named ‘bSetRoundingMode’
          g_Config.bSetRoundingMode = false;
                   ^
../libretro/libretro.cpp:713:19: error: ‘struct Config’ has no member named ‘bUnsafeFuncReplacements’
          g_Config.bUnsafeFuncReplacements = true;
                   ^
../libretro/libretro.cpp:715:19: error: ‘struct Config’ has no member named ‘bUnsafeFuncReplacements’
          g_Config.bUnsafeFuncReplacements = false;
                   ^
../libretro/libretro.cpp:718:19: error: ‘struct Config’ has no member named ‘bUnsafeFuncReplacements’
          g_Config.bUnsafeFuncReplacements = true;
                   ^
../libretro/libretro.cpp:740:30: error: ‘CPU_JIT’ was not declared in this scope
          coreParam.cpuCore = CPU_JIT;
                              ^
../libretro/libretro.cpp:742:30: error: ‘CPU_INTERPRETER’ was not declared in this scope
          coreParam.cpuCore = CPU_INTERPRETER;
                              ^
../libretro/libretro.cpp:745:27: error: ‘CPU_JIT’ was not declared in this scope
       coreParam.cpuCore = CPU_JIT;
                           ^
../libretro/libretro.cpp: In function ‘bool retro_load_game(const retro_game_info*)’:
../libretro/libretro.cpp:897:15: error: invalid new-expression of abstract class type ‘LibretroHost’
    host = new LibretroHost;
               ^
../libretro/libretro.cpp:100:7: note:   because the following virtual functions are pure within ‘LibretroHost’:
 class LibretroHost : public Host {
       ^
In file included from ../libretro/libretro.cpp:12:0:
../Core/Host.h:37:15: note:     virtual bool Host::InitGraphics(std::string*, GraphicsContext**)
  virtual bool InitGraphics(std::string *error_string, GraphicsContext **ctx) = 0;
               ^
../libretro/libretro.cpp:918:24: error: ‘GPU_GLES’ was not declared in this scope
    coreParam.gpuCore = GPU_GLES;
                        ^
../libretro/libretro.cpp:930:55: error: ‘CPU_JIT’ was not declared in this scope
    g_Config.bVertexDecoderJit = (coreParam.cpuCore == CPU_JIT) ? true : false;
                                                       ^
../libretro/libretro.cpp: In function ‘void retro_run()’:
../libretro/libretro.cpp:1125:7: error: ‘libretro_framebuffer’ was not declared in this scope
       libretro_framebuffer = fbo_create_from_native_fbo((GLuint) hw_render.get_current_framebuffer(), libretro_framebuffer);
       ^
../libretro/libretro.cpp:1125:123: error: ‘fbo_create_from_native_fbo’ was not declared in this scope
       libretro_framebuffer = fbo_create_from_native_fbo((GLuint) hw_render.get_current_framebuffer(), libretro_framebuffer);
                                                                                                                           ^
../libretro/libretro.cpp: In function ‘void retro_unload_game()’:
../libretro/libretro.cpp:1146:6: error: ‘libretro_framebuffer’ was not declared in this scope
  if (libretro_framebuffer)
      ^
../libretro/libretro.cpp:1147:35: error: ‘fbo_destroy’ was not declared in this scope
   fbo_destroy(libretro_framebuffer);
                                   ^
../libretro/libretro.cpp:1148:2: error: ‘libretro_framebuffer’ was not declared in this scope
  libretro_framebuffer = NULL;
  ^
../libretro/libretro.cpp: In function ‘bool retro_serialize(void*, size_t)’:
../libretro/libretro.cpp:1181:4: error: ‘SaveStart’ is not a member of ‘SaveState’
    SaveState::SaveStart state;
    ^
../libretro/libretro.cpp:1186:45: error: ‘state’ was not declared in this scope
    size_t sz = CChunkFileReader::MeasurePtr(state);
                                             ^
../libretro/libretro.cpp: In function ‘bool retro_unserialize(const void*, size_t ’:
../libretro/libretro.cpp:1202:4: error: ‘SaveStart’ is not a member of ‘SaveState’
    SaveState::SaveStart state;
    ^
../libretro/libretro.cpp:1203:50: error: ‘state’ was not declared in this scope
    return CChunkFileReader::LoadPtr((u8 *) data, state) == CChunkFileReader::ERROR_NONE;
                                                  ^
Makefile:312: recipe for target '../libretro/libretro.o' failed
make: *** [../libretro/libretro.o] Error 1
make: *** Waiting for unfinished jobs....
make: Leaving directory '/media/gittings/forks/libretro-ppsspp/libretro'
```

### CODE REVIEW

**Comment by SigmaVirus** [comment]
Really great initiative on this, hope this gets solved in the end.

**Comment by julianxhokaxhiu** [comment]
What's up with this? Any news? I was just testing the core today, and still the same old version...

**Comment by CrescendoFang** [comment]
any news with this progress?

**Comment by CrescendoFang** [comment]
is this project really dead by now?

**Comment by hizzlekizzle** [comment]
@CrescendoFang 
It's probably easier at this point just to start over and rebase against upstream rather than sort out all of the merge conflicts and probably end up essentially rebasing anyway.

**Pull request closed without merging**
