### PR TITLE
Update ffmpeg submodule

### PR DESCRIPTION
**Pull request by orbea**
Fixes https://github.com/libretro/libretro-ppsspp/issues/73.

### CODE REVIEW

**Comment by joolswills** [comment]
just to note - on our retropie fork of this repo, I had to revert this at it broke some video playback and caused audio breakage and stuttering in games (note I build ffmpeg from source - the premade libs didn't link for me - and armv6 seemed to miss some includes in the prebuilt folder also).

**Comment by joolswills** [comment]
Sorry to clarify, this was for armv6/v7 target

**Comment by orbea** [comment]
Maybe the associated ffmpeg binaries need to be rebuilt, there should be a script to do it. I don't have the platform so you're going to have to do this yourself.

**Comment by joolswills** [comment]
I already build from source btw - I reverted this PR and all is fine (on arm).

**Comment by orbea** [comment]
Reverting this PR is not a good solution, it should be fixed.

**Comment by joolswills** [comment]
I agree - but I am not sure what the problem is (and have no time to debug it). I was just informing you. We use a fork of this repo for RetroPie currently.

**Comment by orbea** [comment]
Informing someone who doesn't have the hardware to test it on is not going to help much. It would be awesome if you could spend the time to debug it.

**Comment by joolswills** [comment]
Would you preferred I said nothing? :) I don't have the time - nor knowledge of ppsspp so that's all I'm afraid. if lr-ppsspp ever gets updated, I may revisit. I suspect it's a mismatched version of ffmpeg or something (As this PR only updates the ffmpeg version right?).

**Comment by orbea** [comment]
Of course not. :) Just that it'd be awesome if you or someone else who can reproduce this could follow through and also help fix it or at least provide clues on why its broken.  It probably does not require much skills beyond being able to do a simple merge, compiling software and having hardware to test it on.

**Comment by orbea** [comment]
Okay, here are some steps that can be followed to hopefully make it easier.

1. Test upstream ppsspp, is the ffmpeg problem resolved?
2. If it is try merging their ffmpeg repo with the libretro one and seeing if that fixes it for us. 
3. If its broken there too then try compiling ffmpeg by running their build script in the upstream ppsspp ffmpeg repo with the correct environment and seeing if that fixes it.
4. If its still broken, bug them.

**Comment by joolswills** [comment]
thanks.

1. upstream ppsspp is fine
2. that won't work I think as upstream ffmpeg is too new (libretro ppsspp is old and uses some deprecated defines for CODEC_ID etc)

**Pull request merged**
